import { useState } from "react";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import CTAButton from "@/components/CTAButton";
import TrackBadge, { TRACK_META, type Track } from "@/components/TrackBadge";
import {
  Sparkles,
  CalendarDays,
  ShoppingCart,
  Bell,
  MessageSquare,
  Lock,
  RefreshCw,
  BarChart3,
  ChevronDown,
  Star,
  ArrowRight,
  CheckCircle2,
  Zap,
} from "lucide-react";

const APP_URL = import.meta.env.VITE_APP_URL ?? "/mealmate/";

const TRACKS = Object.entries(TRACK_META) as [Track, typeof TRACK_META[Track]][];

const FEATURES = [
  {
    icon: <Sparkles className="h-6 w-6" />,
    title: "AI-Powered Meal Plans",
    desc: "Get a personalised 7-day Indian meal plan generated by GPT-4 in seconds. Every meal is tuned to your health track, region, diet, and cook time.",
    color: "text-orange-500 bg-orange-50",
  },
  {
    icon: <CalendarDays className="h-6 w-6" />,
    title: "Weekly Planner",
    desc: "View breakfast, lunch, snack, and dinner for every day. Lock meals you love, swap ones you don't — the AI adapts.",
    color: "text-blue-500 bg-blue-50",
  },
  {
    icon: <ShoppingCart className="h-6 w-6" />,
    title: "Smart Grocery Lists",
    desc: "One tap turns your meal plan into an organised grocery list — grouped by category, with exact quantities.",
    color: "text-emerald-500 bg-emerald-50",
  },
  {
    icon: <MessageSquare className="h-6 w-6" />,
    title: "AI Nutrition Chat",
    desc: "Ask anything — substitute ingredients, understand nutrition, get cooking tips — your AI dietitian is always on.",
    color: "text-purple-500 bg-purple-50",
  },
  {
    icon: <Bell className="h-6 w-6" />,
    title: "Meal Reminders",
    desc: "Get push notifications before each meal — with your actual dish name. Never miss a scheduled meal again.",
    color: "text-rose-500 bg-rose-50",
  },
  {
    icon: <Lock className="h-6 w-6" />,
    title: "Lock & Swap",
    desc: "Love today's dal? Lock it. Want something different for dinner? Swap it. Your plan, your rules.",
    color: "text-teal-500 bg-teal-50",
  },
  {
    icon: <BarChart3 className="h-6 w-6" />,
    title: "Macro Tracking",
    desc: "See your daily calorie, protein, carb, fat, and fibre totals with a real-time progress bar — no manual entry.",
    color: "text-amber-500 bg-amber-50",
  },
  {
    icon: <RefreshCw className="h-6 w-6" />,
    title: "Auto-Regenerate",
    desc: "New week, new plan. MealCoreAI regenerates your meals using your favourites history, dislikes, and latest preferences.",
    color: "text-indigo-500 bg-indigo-50",
  },
];

const STEPS = [
  {
    step: "01",
    title: "Set your health profile",
    desc: "Tell us your health condition, diet, region, family size, and how much time you have to cook on weekdays vs. weekends.",
    icon: <Zap className="h-8 w-8 text-orange-500" />,
  },
  {
    step: "02",
    title: "Get your AI meal plan",
    desc: "Our AI instantly generates a personalised 7-day Indian meal plan — breakfast, lunch, snack, and dinner — tuned for your health track.",
    icon: <Sparkles className="h-8 w-8 text-orange-500" />,
  },
  {
    step: "03",
    title: "Eat, track & improve",
    desc: "Follow your plan, chat with the AI for help, check nutrition, generate your grocery list, and regenerate each week.",
    icon: <CheckCircle2 className="h-8 w-8 text-orange-500" />,
  },
];

const TESTIMONIALS = [
  {
    name: "Priya S.",
    location: "Bengaluru",
    track: "pcos" as Track,
    text: "I've struggled with PCOS for 4 years and tried countless diets. MealCoreAI finally gave me a plan that actually makes sense for my body — easy-to-cook Indian food I actually enjoy.",
    rating: 5,
  },
  {
    name: "Ramesh K.",
    location: "Chennai",
    track: "diabetes" as Track,
    text: "My doctor recommended reducing sugar and refined carbs. I had no idea what to eat. This app generated a full week of diabetic-friendly South Indian meals in seconds. Remarkable.",
    rating: 5,
  },
  {
    name: "Anika M.",
    location: "Delhi",
    track: "pregnancy" as Track,
    text: "Pregnancy cravings are real! MealCoreAI balances my iron and calcium needs while still recommending dishes I love. The grocery list alone saves me an hour every week.",
    rating: 5,
  },
  {
    name: "Vikram T.",
    location: "Mumbai",
    track: "fitness" as Track,
    text: "High-protein Indian food is hard to find. MealCoreAI nails it. I get paneer, dal, and egg dishes in my plan every day, perfectly balanced for my gym goals.",
    rating: 5,
  },
];

const FAQS = [
  {
    q: "Is MealCoreAI free?",
    a: "Yes — MealCoreAI is completely free to use. Create your health profile, generate meal plans, track nutrition, and use the AI chat without any payment.",
  },
  {
    q: "Does it only work for Indian food?",
    a: "MealCoreAI is purpose-built for Indian cuisine across all regions — North Indian, South Indian, Maharashtrian, Gujarati, Bengali, and more. You choose your regional preference during onboarding.",
  },
  {
    q: "Which health conditions are supported?",
    a: "We currently support 8 health tracks: PCOS, Diabetes (Type 1 & 2), Thyroid (Hypo/Hyper), Pregnancy, Kids (2–12), Fitness/Gym, Cholesterol Management, and General Wellness.",
  },
  {
    q: "Can I use it for my whole family?",
    a: "Absolutely. You can set your family size during onboarding and the grocery list quantities will scale accordingly. Different family members can have different health tracks.",
  },
  {
    q: "How are meal plans personalised?",
    a: "MealCoreAI uses GPT-4 to analyse your health track, diet type (veg/non-veg/eggetarian), region, allergies, cook time, and disliked dishes to generate a plan that fits your life.",
  },
  {
    q: "Can I customise my plan?",
    a: "Yes. You can lock meals you love, swap individual meals, mark dishes as favourites or dislikes, and regenerate your plan at any time. The AI remembers your preferences.",
  },
];

function FAQItem({ q, a }: { q: string; a: string }) {
  const [open, setOpen] = useState(false);
  return (
    <div className="border border-gray-200 rounded-2xl overflow-hidden">
      <button
        onClick={() => setOpen((o) => !o)}
        className="w-full flex items-center justify-between gap-4 px-6 py-5 text-left hover:bg-gray-50 transition-colors"
      >
        <span className="font-semibold text-gray-900 text-sm sm:text-base">{q}</span>
        <ChevronDown
          className={`h-5 w-5 text-gray-400 shrink-0 transition-transform ${open ? "rotate-180" : ""}`}
        />
      </button>
      {open && (
        <div className="px-6 pb-5 text-sm text-gray-600 leading-relaxed border-t border-gray-100 pt-4">
          {a}
        </div>
      )}
    </div>
  );
}

export default function Home() {
  return (
    <div className="min-h-screen bg-white font-sans">
      <Navbar />

      {/* ─── HERO ─────────────────────────────────────────────── */}
      <section className="relative pt-28 pb-20 sm:pt-36 sm:pb-28 overflow-hidden">
        <div className="absolute inset-0 -z-10">
          <div className="absolute inset-0 bg-gradient-to-br from-orange-50 via-white to-rose-50" />
          <div className="absolute top-0 right-0 w-[600px] h-[600px] bg-orange-100/40 rounded-full blur-3xl -translate-y-1/2 translate-x-1/3" />
          <div className="absolute bottom-0 left-0 w-[400px] h-[400px] bg-rose-100/30 rounded-full blur-3xl translate-y-1/3 -translate-x-1/4" />
        </div>

        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="max-w-3xl mx-auto text-center">
            <div className="inline-flex items-center gap-2 px-4 py-1.5 rounded-full bg-orange-100 text-orange-700 text-xs font-semibold uppercase tracking-wide mb-8">
              <Sparkles className="h-3.5 w-3.5" />
              AI-Powered Indian Meal Planning
            </div>

            <h1 className="text-4xl sm:text-5xl lg:text-6xl font-black text-gray-900 leading-tight tracking-tight mb-6">
              Health starts at{" "}
              <span className="relative">
                <span className="text-orange-500">your core</span>
                <svg
                  className="absolute -bottom-2 left-0 w-full"
                  viewBox="0 0 300 12"
                  fill="none"
                  xmlns="http://www.w3.org/2000/svg"
                  aria-hidden="true"
                >
                  <path
                    d="M2 10 C75 2, 225 2, 298 10"
                    stroke="#f97316"
                    strokeWidth="3"
                    strokeLinecap="round"
                    fill="none"
                    opacity="0.5"
                  />
                </svg>
              </span>
            </h1>

            <p className="text-lg sm:text-xl text-gray-600 leading-relaxed mb-10 max-w-2xl mx-auto">
              Personalised 7-day Indian meal plans powered by AI — built for{" "}
              <strong className="text-gray-800">PCOS, Diabetes, Thyroid, Pregnancy</strong>, and 4 more health conditions. 
              Real food. Real results.
            </p>

            <div className="flex flex-col sm:flex-row items-center justify-center gap-3 mb-12">
              <CTAButton href={APP_URL} size="lg">
                Start for free <ArrowRight className="h-4 w-4" />
              </CTAButton>
              <CTAButton href="#how-it-works" variant="outline" size="lg">
                See how it works
              </CTAButton>
            </div>

            <div className="flex flex-wrap items-center justify-center gap-2">
              {(["pcos", "diabetes", "thyroid", "pregnancy", "fitness", "cholesterol", "kids", "general"] as Track[]).map((t) => (
                <TrackBadge key={t} track={t} size="sm" />
              ))}
            </div>
          </div>

          {/* ─── App Preview Card ────────────────────────────────── */}
          <div className="mt-16 max-w-2xl mx-auto">
            <div className="bg-white rounded-3xl shadow-2xl shadow-orange-100 border border-gray-100 overflow-hidden">
              <div className="bg-gradient-to-r from-orange-500 to-rose-500 px-6 py-4 flex items-center gap-3">
                <img src="./logo.svg" alt="MealCoreAI" className="h-7 w-7" />
                <div>
                  <div className="text-white font-bold text-sm">MealCoreAI</div>
                  <div className="text-orange-100 text-xs">Today's meal plan — PCOS track</div>
                </div>
              </div>
              <div className="p-6 grid grid-cols-2 gap-3">
                {[
                  { meal: "Breakfast", dish: "Moong Dal Chilla", cal: "280 kcal", time: "20 min", icon: "🌅" },
                  { meal: "Lunch", dish: "Palak Paneer + Roti", cal: "420 kcal", time: "30 min", icon: "☀️" },
                  { meal: "Snack", dish: "Roasted Makhana", cal: "120 kcal", time: "5 min", icon: "🍿" },
                  { meal: "Dinner", dish: "Methi Dal + Brown Rice", cal: "380 kcal", time: "25 min", icon: "🌙" },
                ].map(({ meal, dish, cal, time, icon }) => (
                  <div key={meal} className="bg-gray-50 rounded-2xl p-4 hover:bg-orange-50 transition-colors">
                    <div className="text-xl mb-2">{icon}</div>
                    <div className="text-xs font-semibold text-orange-500 uppercase tracking-wide mb-1">{meal}</div>
                    <div className="text-sm font-bold text-gray-800 leading-tight mb-2">{dish}</div>
                    <div className="flex items-center gap-2 text-xs text-gray-500">
                      <span>🔥 {cal}</span>
                      <span>⏱ {time}</span>
                    </div>
                  </div>
                ))}
              </div>
              <div className="px-6 pb-5">
                <div className="bg-orange-50 rounded-2xl p-4">
                  <div className="flex items-center justify-between mb-2">
                    <span className="text-xs font-semibold text-gray-700">Daily nutrition progress</span>
                    <span className="text-xs text-orange-600 font-bold">1,200 / 1,500 kcal</span>
                  </div>
                  <div className="h-2 bg-orange-100 rounded-full overflow-hidden">
                    <div className="h-full bg-gradient-to-r from-orange-400 to-rose-400 rounded-full" style={{ width: "80%" }} />
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      {/* ─── STATS BAR ─────────────────────────────────────────── */}
      <section className="bg-gray-950 py-10">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-2 md:grid-cols-4 gap-8 text-center">
            {[
              { value: "8", label: "Health Tracks" },
              { value: "500+", label: "Indian Dishes" },
              { value: "GPT-4", label: "AI Engine" },
              { value: "100%", label: "Free to Use" },
            ].map(({ value, label }) => (
              <div key={label}>
                <div className="text-3xl sm:text-4xl font-black text-orange-500">{value}</div>
                <div className="text-sm text-gray-400 mt-1 font-medium">{label}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── FEATURES ──────────────────────────────────────────── */}
      <section id="features" className="py-24 bg-white">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-100 text-orange-600 text-xs font-semibold uppercase tracking-wide mb-4">
              Everything you need
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-gray-900 mb-4">
              Built for real Indian health journeys
            </h2>
            <p className="text-lg text-gray-500 max-w-2xl mx-auto">
              From AI meal generation to grocery lists and push reminders — MealCoreAI is your complete nutrition companion.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {FEATURES.map(({ icon, title, desc, color }) => (
              <div
                key={title}
                className="group bg-white border border-gray-100 rounded-2xl p-6 hover:shadow-lg hover:-translate-y-1 transition-all duration-200"
              >
                <div className={`inline-flex items-center justify-center w-12 h-12 rounded-2xl mb-4 ${color}`}>
                  {icon}
                </div>
                <h3 className="font-bold text-gray-900 mb-2 text-sm">{title}</h3>
                <p className="text-xs text-gray-500 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── HEALTH TRACKS ─────────────────────────────────────── */}
      <section id="tracks" className="py-24 bg-gray-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-100 text-orange-600 text-xs font-semibold uppercase tracking-wide mb-4">
              8 Health Tracks
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-gray-900 mb-4">
              Your health condition. Your plan.
            </h2>
            <p className="text-lg text-gray-500 max-w-2xl mx-auto">
              MealCoreAI understands the dietary needs of each condition — so every meal works for you, not against you.
            </p>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-5">
            {TRACKS.map(([key, meta]) => {
              const descriptions: Record<Track, string> = {
                pcos: "Low-GI, anti-inflammatory dishes rich in fibre and lean protein to manage insulin resistance.",
                diabetes: "Low glycaemic index meals with complex carbs, high fibre, and controlled portion sizes.",
                thyroid: "Selenium and iodine-rich meals, avoiding goitrogens in excess for thyroid support.",
                pregnancy: "Iron, calcium, folate, and DHA-rich meals with pregnancy-safe ingredients.",
                kids: "Nutrient-dense, fun, easy-to-eat meals for healthy growth in children aged 2–12.",
                fitness: "High-protein, muscle-building Indian meals for gym-goers and active adults.",
                cholesterol: "Heart-healthy, low-saturated-fat meals rich in omega-3s and soluble fibre.",
                general: "Balanced, wholesome Indian meals for everyday wellness and energy.",
              };
              return (
                <div key={key} className="bg-white border border-gray-100 rounded-2xl p-6 hover:shadow-md hover:-translate-y-0.5 transition-all duration-200">
                  <div className="text-3xl mb-3">{meta.emoji}</div>
                  <TrackBadge track={key} size="sm" />
                  <p className="mt-3 text-xs text-gray-500 leading-relaxed">{descriptions[key]}</p>
                </div>
              );
            })}
          </div>
        </div>
      </section>

      {/* ─── HOW IT WORKS ──────────────────────────────────────── */}
      <section id="how-it-works" className="py-24 bg-white">
        <div className="max-w-5xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-100 text-orange-600 text-xs font-semibold uppercase tracking-wide mb-4">
              Simple process
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-gray-900 mb-4">
              Up and running in 3 steps
            </h2>
            <p className="text-lg text-gray-500 max-w-xl mx-auto">
              From sign-up to your first personalised meal plan in under 2 minutes.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-8 relative">
            <div className="hidden md:block absolute top-10 left-[calc(16.67%+24px)] right-[calc(16.67%+24px)] h-0.5 bg-gradient-to-r from-orange-200 via-orange-300 to-orange-200" />
            {STEPS.map(({ step, title, desc, icon }) => (
              <div key={step} className="relative text-center">
                <div className="relative inline-flex items-center justify-center w-20 h-20 rounded-2xl bg-orange-50 border-2 border-orange-100 mb-5 mx-auto">
                  {icon}
                  <span className="absolute -top-3 -right-3 w-7 h-7 rounded-full bg-orange-500 text-white text-xs font-black flex items-center justify-center">
                    {step}
                  </span>
                </div>
                <h3 className="font-bold text-gray-900 mb-2">{title}</h3>
                <p className="text-sm text-gray-500 leading-relaxed">{desc}</p>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── TESTIMONIALS ──────────────────────────────────────── */}
      <section className="py-24 bg-gradient-to-br from-orange-50 to-rose-50">
        <div className="max-w-6xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white text-orange-600 text-xs font-semibold uppercase tracking-wide border border-orange-200 mb-4">
              Real stories
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-gray-900 mb-4">
              Loved by health-conscious Indians
            </h2>
          </div>

          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {TESTIMONIALS.map(({ name, location, track, text, rating }) => (
              <div key={name} className="bg-white rounded-2xl p-6 shadow-sm border border-orange-50 flex flex-col">
                <div className="flex gap-0.5 mb-4">
                  {Array.from({ length: rating }).map((_, i) => (
                    <Star key={i} className="h-4 w-4 fill-orange-400 text-orange-400" />
                  ))}
                </div>
                <p className="text-sm text-gray-600 leading-relaxed flex-1 mb-5">"{text}"</p>
                <div className="flex items-center gap-3">
                  <div className="w-9 h-9 rounded-full bg-orange-100 flex items-center justify-center text-sm font-bold text-orange-600">
                    {name[0]}
                  </div>
                  <div>
                    <div className="text-sm font-bold text-gray-900">{name}</div>
                    <div className="text-xs text-gray-400">{location}</div>
                  </div>
                  <div className="ml-auto">
                    <TrackBadge track={track} size="sm" />
                  </div>
                </div>
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* ─── FAQ ────────────────────────────────────────────────── */}
      <section id="faq" className="py-24 bg-white">
        <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-orange-100 text-orange-600 text-xs font-semibold uppercase tracking-wide mb-4">
              Got questions?
            </div>
            <h2 className="text-3xl sm:text-4xl font-black text-gray-900 mb-4">
              Frequently asked questions
            </h2>
          </div>

          <div className="space-y-3">
            {FAQS.map(({ q, a }) => (
              <FAQItem key={q} q={q} a={a} />
            ))}
          </div>
        </div>
      </section>

      {/* ─── CTA ─────────────────────────────────────────────────── */}
      <section className="py-24 bg-gray-950 relative overflow-hidden">
        <div className="absolute inset-0 -z-0">
          <div className="absolute top-0 left-1/2 w-[600px] h-[600px] bg-orange-500/10 rounded-full blur-3xl -translate-x-1/2 -translate-y-1/2" />
        </div>
        <div className="relative max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="text-5xl mb-6">🍛</div>
          <h2 className="text-3xl sm:text-4xl font-black text-white mb-5">
            Ready to eat smarter?
          </h2>
          <p className="text-lg text-gray-400 mb-10 max-w-xl mx-auto leading-relaxed">
            Join thousands of Indians taking control of their health — one personalised meal at a time. Free, forever.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <CTAButton href={APP_URL} size="lg">
              Get started free <ArrowRight className="h-4 w-4" />
            </CTAButton>
            <span className="text-sm text-gray-600">No credit card. No signup fees.</span>
          </div>
          <div className="mt-10 flex flex-wrap items-center justify-center gap-6 text-sm text-gray-500">
            {["✓ Free forever", "✓ 8 health tracks", "✓ 500+ Indian dishes", "✓ Push reminders"].map((item) => (
              <span key={item}>{item}</span>
            ))}
          </div>
        </div>
      </section>

      <Footer />
    </div>
  );
}
